NOVEL_PLATFORMS = {
    "qidian": {
        "name": "起点中文网",
        "base_url": "https://www.qidian.com",
        "search_url": "https://www.qidian.com/so/{keyword}.html",
        "entry_strategy": "search",
        "request_template": {
            "method": "GET",
            "headers": {},
            "params": {},
        },
        "parse_rules": {
            "list_selector": ".book-img-text ul li",
            "title_selector": ".book-mid-info h4 a",
            "author_selector": ".book-mid-info .author a.name",
            "link_selector": ".book-mid-info h4 a",
            "summary_selector": ".book-mid-info .intro",
            "content_selector": ".read-content .text-wrap",
            "chapter_list_selector": ".volume-wrap .cf li a",
        },
        "rate_limit": 2.0,
        "update_frequency": "daily",
    },
    "jjwxc": {
        "name": "晋江文学城",
        "base_url": "https://www.jjwxc.net",
        "search_url": "http://search.jjwxc.net/search.php?kw={keyword}&t=1",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result-list .search-result-item",
            "title_selector": ".search-result-item .title a",
            "author_selector": ".search-result-item .author a",
            "link_selector": ".search-result-item .title a",
            "summary_selector": ".search-result-item .intro",
            "content_selector": ".noveltext",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.5,
        "update_frequency": "daily",
    },
    "zongheng": {
        "name": "纵横中文网",
        "base_url": "https://www.zongheng.com",
        "search_url": "http://search.zongheng.com/s?keyword={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result-list .search-tab-list",
            "title_selector": ".search-tab-list .tit a",
            "author_selector": ".search-tab-list .author a",
            "link_selector": ".search-tab-list .tit a",
            "summary_selector": ".search-tab-list .des",
            "content_selector": ".reader_con",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.0,
        "update_frequency": "daily",
    },
    "fanqie": {
        "name": "番茄小说",
        "base_url": "https://fanqienovel.com",
        "search_url": "https://fanqienovel.com/search/{keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result-item",
            "title_selector": ".book-name",
            "author_selector": ".author-name",
            "link_selector": ".book-name",
            "summary_selector": ".book-summary",
            "content_selector": ".content",
            "chapter_list_selector": ".chapter-item a",
        },
        "rate_limit": 1.5,
        "update_frequency": "daily",
    },
    "qimao": {
        "name": "七猫免费小说",
        "base_url": "https://www.qimao.com",
        "search_url": "https://www.qimao.com/search?query={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".book-list-item",
            "title_selector": ".book-title",
            "author_selector": ".book-author",
            "link_selector": ".book-title",
            "summary_selector": ".book-desc",
            "content_selector": ".chapter-content",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.0,
        "update_frequency": "daily",
    },
    "17k": {
        "name": "17K小说网",
        "base_url": "https://www.17k.com",
        "search_url": "https://search.17k.com/search?keyword={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-list .item",
            "title_selector": ".title a",
            "author_selector": ".author a",
            "link_selector": ".title a",
            "summary_selector": ".intro",
            "content_selector": ".p-content",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.0,
        "update_frequency": "every_2_days",
    },
    "xiangxiang": {
        "name": "潇湘书院",
        "base_url": "https://www.xxsy.net",
        "search_url": "https://www.xxsy.net/search?kw={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".book-name a",
            "author_selector": ".author-name",
            "link_selector": ".book-name a",
            "summary_selector": ".book-intro",
            "content_selector": ".chapter-content",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.0,
        "update_frequency": "every_2_days",
    },
    "hongxiu": {
        "name": "红袖添香",
        "base_url": "https://www.hongxiu.com",
        "search_url": "https://www.hongxiu.com/search?kw={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".book-name a",
            "author_selector": ".author-name",
            "link_selector": ".book-name a",
            "summary_selector": ".book-intro",
            "content_selector": ".chapter-content",
            "chapter_list_selector": ".chapter-list a",
        },
        "rate_limit": 2.0,
        "update_frequency": "every_2_days",
    },
    "wangyue": {
        "name": "网易云阅读",
        "base_url": "https://yuedu.163.com",
        "search_url": "https://yuedu.163.com/search?keyword={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-list .item",
            "title_selector": ".title a",
            "author_selector": ".author",
            "link_selector": ".title a",
            "summary_selector": ".desc",
            "content_selector": ".article-content",
            "chapter_list_selector": ".chapter a",
        },
        "rate_limit": 2.5,
        "update_frequency": "every_3_days",
    },
    "qqread": {
        "name": "QQ阅读",
        "base_url": "https://book.qq.com",
        "search_url": "https://book.qq.com/search?keyword={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".book-list .item",
            "title_selector": ".book-name",
            "author_selector": ".author-name",
            "link_selector": ".book-name",
            "summary_selector": ".book-desc",
            "content_selector": ".content",
            "chapter_list_selector": ".chapter a",
        },
        "rate_limit": 2.0,
        "update_frequency": "daily",
    },
    "baidu_tieba_novel": {
        "name": "百度贴吧小说吧",
        "base_url": "https://tieba.baidu.com",
        "search_url": "https://tieba.baidu.com/f?kw={keyword}&ie=utf-8",
        "entry_strategy": "directory",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".thread_list li",
            "title_selector": ".threadlist_title a",
            "author_selector": ".threadlist_author span",
            "link_selector": ".threadlist_title a",
            "summary_selector": ".threadlist_abs",
            "content_selector": ".d_post_content",
            "chapter_list_selector": ".core_reply a",
        },
        "rate_limit": 3.0,
        "update_frequency": "daily",
    },
    "douban_read": {
        "name": "豆瓣阅读",
        "base_url": "https://read.douban.com",
        "search_url": "https://read.douban.com/search?q={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result-list .item",
            "title_selector": ".title a",
            "author_selector": ".author-item a",
            "link_selector": ".title a",
            "summary_selector": ".abstract",
            "content_selector": ".article-content",
            "chapter_list_selector": ".chapter-item a",
        },
        "rate_limit": 2.5,
        "update_frequency": "every_3_days",
    },
}

DOC_PLATFORMS = {
    "baidu_wenku": {
        "name": "百度文库",
        "base_url": "https://wenku.baidu.com",
        "search_url": "https://wenku.baidu.com/search?word={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .doc-item",
            "title_selector": ".doc-title a",
            "author_selector": ".doc-info .author",
            "link_selector": ".doc-title a",
            "summary_selector": ".doc-summary",
            "content_selector": ".reader-content",
        },
        "rate_limit": 3.0,
        "update_frequency": "every_3_days",
    },
    "docin": {
        "name": "豆丁网",
        "base_url": "https://www.docin.com",
        "search_url": "https://www.docin.com/search.do?keyword={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".title a",
            "author_selector": ".author",
            "link_selector": ".title a",
            "summary_selector": ".desc",
            "content_selector": ".doc-content",
        },
        "rate_limit": 3.0,
        "update_frequency": "every_3_days",
    },
    "doc88": {
        "name": "道客巴巴",
        "base_url": "https://www.doc88.com",
        "search_url": "https://www.doc88.com/s?q={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-list .item",
            "title_selector": ".title a",
            "author_selector": ".meta .author",
            "link_selector": ".title a",
            "summary_selector": ".desc",
            "content_selector": ".content",
        },
        "rate_limit": 3.0,
        "update_frequency": "every_3_days",
    },
    "360doc": {
        "name": "360doc",
        "base_url": "http://www.360doc.com",
        "search_url": "http://www.360doc.com/search.do?kw={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".searchlist .art",
            "title_selector": ".art-title a",
            "author_selector": ".art-info .name",
            "link_selector": ".art-title a",
            "summary_selector": ".art-desc",
            "content_selector": "#artContent",
        },
        "rate_limit": 2.5,
        "update_frequency": "every_3_days",
    },
    "wenkoo": {
        "name": "文库网",
        "base_url": "https://www.wenkoo.cn",
        "search_url": "https://www.wenkoo.cn/search?q={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".doc-title a",
            "author_selector": ".doc-info span",
            "link_selector": ".doc-title a",
            "summary_selector": ".doc-desc",
            "content_selector": ".doc-content",
        },
        "rate_limit": 2.5,
        "update_frequency": "weekly",
    },
    "ishare": {
        "name": "爱问共享",
        "base_url": "https://ishare.iask.sina.com.cn",
        "search_url": "https://ishare.iask.sina.com.cn/search/{keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".doc-title a",
            "author_selector": ".doc-author",
            "link_selector": ".doc-title a",
            "summary_selector": ".doc-desc",
            "content_selector": ".doc-content",
        },
        "rate_limit": 3.0,
        "update_frequency": "weekly",
    },
    "book118": {
        "name": "原创力文档",
        "base_url": "https://max.book118.com",
        "search_url": "https://max.book118.com/index.php?g=Search&q={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-result .item",
            "title_selector": ".title a",
            "author_selector": ".info span",
            "link_selector": ".title a",
            "summary_selector": ".desc",
            "content_selector": ".content",
        },
        "rate_limit": 3.0,
        "update_frequency": "weekly",
    },
    "renrendoc": {
        "name": "人人文档",
        "base_url": "https://www.renrendoc.com",
        "search_url": "https://www.renrendoc.com/search.html?kw={keyword}",
        "entry_strategy": "search",
        "request_template": {"method": "GET", "headers": {}, "params": {}},
        "parse_rules": {
            "list_selector": ".search-list .item",
            "title_selector": ".doc-title a",
            "author_selector": ".doc-info",
            "link_selector": ".doc-title a",
            "summary_selector": ".doc-desc",
            "content_selector": ".doc-content",
        },
        "rate_limit": 2.5,
        "update_frequency": "weekly",
    },
}
