package com.emergency.dispatch.service.impl;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.emergency.common.dto.GeoPoint;
import com.emergency.common.dto.LoginUser;
import com.emergency.common.dto.PageResult;
import com.emergency.common.enums.DispatchStatus;
import com.emergency.common.enums.TeamStatus;
import com.emergency.common.exception.BusinessException;
import com.emergency.common.result.Result;
import com.emergency.common.result.ResultCode;
import com.emergency.common.util.IdGenerator;
import com.emergency.common.util.SecurityUtils;
import com.emergency.dispatch.dto.DispatchConflictResult;
import com.emergency.dispatch.dto.DispatchGenerateRequest;
import com.emergency.dispatch.entity.DispatchPlan;
import com.emergency.dispatch.entity.RescueTeam;
import com.emergency.dispatch.entity.TeamAssignment;
import com.emergency.dispatch.feign.IncidentFeignClient;
import com.emergency.dispatch.mapper.DispatchPlanMapper;
import com.emergency.dispatch.mapper.RescueTeamMapper;
import com.emergency.dispatch.mapper.TeamAssignmentMapper;
import com.emergency.dispatch.service.DispatchService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.redisson.api.RLock;
import org.redisson.api.RedissonClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class DispatchServiceImpl implements DispatchService {

    private final DispatchPlanMapper dispatchPlanMapper;
    private final RescueTeamMapper rescueTeamMapper;
    private final TeamAssignmentMapper teamAssignmentMapper;
    private final IncidentFeignClient incidentFeignClient;
    private final RedissonClient redissonClient;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Long autoGenerateDispatch(Long incidentId) {
        Result<?> incidentResult = incidentFeignClient.getIncidentById(incidentId);
        if (!incidentResult.isSuccess() || incidentResult.getData() == null) {
            throw new BusinessException("灾情信息不存在");
        }

        var incidentData = (java.util.Map<String, Object>) incidentResult.getData();
        Double lng = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lng")).doubleValue();
        Double lat = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lat")).doubleValue();

        List<RescueTeam> availableTeams = getAvailableTeams(lng, lat, 50.0, 10);
        if (availableTeams.isEmpty()) {
            availableTeams = getAvailableTeams(lng, lat, 100.0, 10);
        }

        if (availableTeams.isEmpty()) {
            throw new BusinessException("附近50公里内无可用救援力量");
        }

        DispatchGenerateRequest request = new DispatchGenerateRequest();
        request.setIncidentId(incidentId);
        request.setTeamIds(availableTeams.stream().map(RescueTeam::getId).limit(5).collect(Collectors.toList()));
        request.setTaskDescription("自动生成的救援任务");

        DispatchPlan plan = generateDispatchPlan(request);
        return plan.getId();
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public DispatchPlan generateDispatchPlan(DispatchGenerateRequest request) {
        LoginUser currentUser = SecurityUtils.getCurrentUser();
        if (currentUser == null) {
            throw new BusinessException(ResultCode.UNAUTHORIZED);
        }

        List<Long> teamIds = request.getTeamIds();
        if (teamIds == null || teamIds.isEmpty()) {
            Result<?> incidentResult = incidentFeignClient.getIncidentById(request.getIncidentId());
            if (incidentResult.isSuccess() && incidentResult.getData() != null) {
                var incidentData = (java.util.Map<String, Object>) incidentResult.getData();
                Double lng = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lng")).doubleValue();
                Double lat = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lat")).doubleValue();
                List<RescueTeam> teams = getAvailableTeams(lng, lat, request.getMaxRadius().doubleValue(), 10);
                teamIds = teams.stream().map(RescueTeam::getId).limit(5).collect(Collectors.toList());
            }
        }

        DispatchConflictResult conflictResult = checkConflicts(request.getIncidentId(), teamIds);
        if (conflictResult.isHasConflict()) {
            throw new BusinessException("存在调度冲突: " + String.join("; ", conflictResult.getConflictDetails()));
        }

        String teamIdStr = teamIds.stream().map(String::valueOf).collect(Collectors.joining(","));
        List<Long> availableIds = rescueTeamMapper.selectAvailableTeamIds(teamIdStr);
        if (availableIds.size() < teamIds.size()) {
            List<Long> unavailable = new ArrayList<>(teamIds);
            unavailable.removeAll(availableIds);
            throw new BusinessException(ResultCode.TEAM_NOT_AVAILABLE,
                    "队伍不可用: " + unavailable);
        }

        DispatchPlan plan = new DispatchPlan();
        plan.setDispatchNo(IdGenerator.generateDispatchNo());
        plan.setIncidentId(request.getIncidentId());
        plan.setTitle("救援调度方案");
        plan.setStatus(DispatchStatus.DRAFT);
        plan.setPriority(request.getIncidentLevel() != null ? 5 - request.getIncidentLevel() : 3);
        plan.setRequiredLevel(request.getIncidentLevel() != null ? request.getIncidentLevel() : 4);
        plan.setTaskDescription(request.getTaskDescription());
        plan.setDangerWarning(request.getDangerWarning());
        plan.setCreatedByOrgId(currentUser.getOrganizationId());
        dispatchPlanMapper.insert(plan);

        int totalPersonnel = 0;
        double maxDistance = 0;

        Result<?> incidentResult = incidentFeignClient.getIncidentById(request.getIncidentId());
        GeoPoint incidentPoint = null;
        if (incidentResult.isSuccess() && incidentResult.getData() != null) {
            var incidentData = (java.util.Map<String, Object>) incidentResult.getData();
            Double lng = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lng")).doubleValue();
            Double lat = ((Number) ((java.util.Map<String, Object>) incidentData.get("locationPoint")).get("lat")).doubleValue();
            incidentPoint = new GeoPoint(lng, lat);
        }

        for (Long teamId : teamIds) {
            String lockKey = "dispatch:team:" + teamId;
            RLock lock = redissonClient.getLock(lockKey);
            try {
                if (!lock.tryLock(3, 30, TimeUnit.SECONDS)) {
                    throw new BusinessException("队伍 " + teamId + " 正在被调度，请稍后再试");
                }
                try {
                    RescueTeam team = rescueTeamMapper.selectById(teamId);
                    TeamAssignment assignment = new TeamAssignment();
                    assignment.setDispatchPlanId(plan.getId());
                    assignment.setTeamId(teamId);
                    assignment.setTeamName(team.getTeamName());
                    assignment.setTeamCount(team.getTeamSize());
                    assignment.setAssignedAt(LocalDateTime.now());
                    assignment.setStatus("ASSIGNED");
                    teamAssignmentMapper.insert(assignment);

                    rescueTeamMapper.updateStatusAndTaskCount(teamId, TeamStatus.DISPATCHED, 1, currentUser.getUserId());

                    totalPersonnel += team.getTeamSize();
                    if (incidentPoint != null && team.getLocationPoint() != null) {
                        double distance = team.getLocationPoint().distanceTo(incidentPoint);
                        maxDistance = Math.max(maxDistance, distance);
                    }
                } finally {
                    lock.unlock();
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new BusinessException("系统异常");
            }
        }

        plan.setEstimatedDistance(BigDecimal.valueOf(maxDistance));
        plan.setEstimatedDuration((int) (maxDistance / 60 * 60));
        plan.setEstimatedArrivalTime(LocalDateTime.now().plusMinutes((long) (maxDistance / 60 * 60)));
        plan.setDispatchStrategy(String.format("调度%d支队伍，共%d人", teamIds.size(), totalPersonnel));
        dispatchPlanMapper.updateById(plan);

        log.info("生成调度方案成功: dispatchId={}, incidentId={}, teamCount={}",
                plan.getId(), request.getIncidentId(), teamIds.size());

        return plan;
    }

    @Override
    public DispatchConflictResult checkConflicts(Long incidentId, List<Long> teamIds) {
        DispatchConflictResult result = new DispatchConflictResult();
        result.setHasConflict(false);
        result.setConflictTeamIds(new ArrayList<>());
        result.setConflictDetails(new ArrayList<>());
        result.setSuggestedAlternativeTeamIds(new ArrayList<>());

        if (teamIds == null || teamIds.isEmpty()) {
            return result;
        }

        String teamIdStr = teamIds.stream().map(String::valueOf).collect(Collectors.joining(","));
        List<Long> busyTeamIds = teamAssignmentMapper.selectBusyTeamIds(teamIdStr);

        for (Long teamId : busyTeamIds) {
            RescueTeam team = rescueTeamMapper.selectById(teamId);
            List<TeamAssignment> assignments = teamAssignmentMapper.selectByTeamId(teamId);
            TeamAssignment current = assignments.stream()
                    .filter(a -> "ASSIGNED".equals(a.getStatus()) || "DEPARTED".equals(a.getStatus())
                            || "ON_SCENE".equals(a.getStatus()) || "WORKING".equals(a.getStatus()))
                    .findFirst().orElse(null);

            if (current != null && !current.getDispatchPlanId().equals(incidentId)) {
                result.setHasConflict(true);
                result.getConflictTeamIds().add(teamId);
                result.getConflictDetails().add(
                        String.format("队伍[%s]已被调度至方案#%d",
                                team.getTeamName(), current.getDispatchPlanId()));
            }
        }

        return result;
    }

    @Override
    public DispatchPlan getDispatchById(Long id) {
        DispatchPlan plan = dispatchPlanMapper.selectById(id);
        if (plan == null) {
            throw new BusinessException(ResultCode.DISPATCH_NOT_FOUND);
        }
        return plan;
    }

    @Override
    public DispatchPlan getDispatchByNo(String dispatchNo) {
        return dispatchPlanMapper.selectByDispatchNo(dispatchNo);
    }

    @Override
    public List<DispatchPlan> getDispatchByIncidentId(Long incidentId) {
        return dispatchPlanMapper.selectByIncidentId(incidentId);
    }

    @Override
    public List<DispatchPlan> getActiveDispatchPlans() {
        return dispatchPlanMapper.selectActivePlans();
    }

    @Override
    public PageResult<DispatchPlan> queryDispatchPlans(int pageNum, int pageSize, Integer status, String regionCode) {
        IPage<DispatchPlan> page = new Page<>(pageNum, pageSize);
        dispatchPlanMapper.selectPage(page, null);
        return PageResult.of(page);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public DispatchPlan updateDispatchStatus(Long id, Integer status) {
        DispatchPlan plan = getDispatchById(id);
        dispatchPlanMapper.updateStatus(id, status, SecurityUtils.getCurrentUserId());
        plan.setStatus(DispatchStatus.fromCode(status));

        if (status == DispatchStatus.DISPATCHED.getCode()) {
            List<TeamAssignment> assignments = teamAssignmentMapper.selectByPlanId(id);
            for (TeamAssignment assignment : assignments) {
                assignment.setDepartedAt(LocalDateTime.now());
                assignment.setStatus("DEPARTED");
                teamAssignmentMapper.updateById(assignment);
                rescueTeamMapper.updateStatusAndTaskCount(
                        assignment.getTeamId(), TeamStatus.DISPATCHED, 0, SecurityUtils.getCurrentUserId());
            }
        } else if (status == DispatchStatus.COMPLETED.getCode()) {
            List<TeamAssignment> assignments = teamAssignmentMapper.selectByPlanId(id);
            for (TeamAssignment assignment : assignments) {
                assignment.setCompletedAt(LocalDateTime.now());
                assignment.setStatus("COMPLETED");
                teamAssignmentMapper.updateById(assignment);
                rescueTeamMapper.updateStatusAndTaskCount(
                        assignment.getTeamId(), TeamStatus.AVAILABLE, -1, SecurityUtils.getCurrentUserId());
            }
        }

        return plan;
    }

    @Override
    public List<RescueTeam> getAvailableTeams(Double lng, Double lat, Double radius, Integer limit) {
        return rescueTeamMapper.selectAvailableTeamsNearby(lng, lat, radius, TeamStatus.AVAILABLE, limit);
    }

    @Override
    public RescueTeam getTeamById(Long id) {
        return rescueTeamMapper.selectById(id);
    }

    @Override
    public List<RescueTeam> getAllTeams() {
        LoginUser user = SecurityUtils.getCurrentUser();
        if (user != null && user.getAccessibleOrgIds() != null) {
            String orgIds = user.getAccessibleOrgIds().stream()
                    .map(String::valueOf)
                    .collect(Collectors.joining(","));
            return rescueTeamMapper.selectByOrgIds(orgIds);
        }
        return rescueTeamMapper.selectList(null);
    }

    @Override
    public List<TeamAssignment> getTeamAssignmentsByPlanId(Long planId) {
        return teamAssignmentMapper.selectByPlanId(planId);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean cancelDispatch(Long id, String reason) {
        DispatchPlan plan = getDispatchById(id);
        if (plan.getStatus() == DispatchStatus.COMPLETED || plan.getStatus() == DispatchStatus.CANCELLED) {
            throw new BusinessException("该调度方案无法取消");
        }

        dispatchPlanMapper.updateStatus(id, DispatchStatus.CANCELLED.getCode(), SecurityUtils.getCurrentUserId());

        List<TeamAssignment> assignments = teamAssignmentMapper.selectByPlanId(id);
        for (TeamAssignment assignment : assignments) {
            if (!"COMPLETED".equals(assignment.getStatus())) {
                assignment.setStatus("CANCELLED");
                teamAssignmentMapper.updateById(assignment);
                rescueTeamMapper.updateStatusAndTaskCount(
                        assignment.getTeamId(), TeamStatus.AVAILABLE, -1, SecurityUtils.getCurrentUserId());
            }
        }

        log.info("取消调度方案: dispatchId={}, reason={}", id, reason);
        return true;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean reassignTeam(Long assignmentId, Long newTeamId) {
        TeamAssignment oldAssignment = teamAssignmentMapper.selectById(assignmentId);
        if (oldAssignment == null) {
            throw new BusinessException("调度分配不存在");
        }

        RescueTeam newTeam = rescueTeamMapper.selectById(newTeamId);
        if (newTeam.getStatus() != TeamStatus.AVAILABLE) {
            throw new BusinessException(ResultCode.TEAM_NOT_AVAILABLE);
        }

        RescueTeam oldTeam = rescueTeamMapper.selectById(oldAssignment.getTeamId());
        rescueTeamMapper.updateStatusAndTaskCount(oldTeam.getId(), TeamStatus.AVAILABLE, -1,
                SecurityUtils.getCurrentUserId());

        oldAssignment.setTeamId(newTeamId);
        oldAssignment.setTeamName(newTeam.getTeamName());
        oldAssignment.setTeamCount(newTeam.getTeamSize());
        oldAssignment.setAssignedAt(LocalDateTime.now());
        oldAssignment.setConflictInfo("原队伍:" + oldTeam.getTeamName() + " 变更为:" + newTeam.getTeamName());
        teamAssignmentMapper.updateById(oldAssignment);

        rescueTeamMapper.updateStatusAndTaskCount(newTeamId, TeamStatus.DISPATCHED, 1,
                SecurityUtils.getCurrentUserId());

        log.info("重新分配队伍: assignmentId={}, oldTeam={}, newTeam={}",
                assignmentId, oldTeam.getTeamName(), newTeam.getTeamName());
        return true;
    }
}
