nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'Cache-Control']
        expose_headers: ['Content-Disposition', 'X-Total-Count', 'X-Page-Count']
        max_age: 86400
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
            max_age: 86400
            allow_credentials: true
