package com.emergency.dispatch.service;

import com.emergency.common.dto.PageResult;
import com.emergency.common.enums.TeamStatus;
import com.emergency.dispatch.dto.DispatchConflictResult;
import com.emergency.dispatch.dto.DispatchGenerateRequest;
import com.emergency.dispatch.entity.DispatchPlan;
import com.emergency.dispatch.entity.RescueTeam;
import com.emergency.dispatch.entity.TeamAssignment;

import java.util.List;

public interface DispatchService {

    Long autoGenerateDispatch(Long incidentId);

    DispatchPlan generateDispatchPlan(DispatchGenerateRequest request);

    DispatchPlan getDispatchById(Long id);

    DispatchPlan getDispatchByNo(String dispatchNo);

    List<DispatchPlan> getDispatchByIncidentId(Long incidentId);

    List<DispatchPlan> getActiveDispatchPlans();

    PageResult<DispatchPlan> queryDispatchPlans(int pageNum, int pageSize, Integer status, String regionCode);

    DispatchPlan updateDispatchStatus(Long id, Integer status);

    DispatchConflictResult checkConflicts(Long incidentId, List<Long> teamIds);

    List<RescueTeam> getAvailableTeams(Double lng, Double lat, Double radius, Integer limit);

    RescueTeam getTeamById(Long id);

    List<RescueTeam> getAllTeams();

    List<TeamAssignment> getTeamAssignmentsByPlanId(Long planId);

    boolean cancelDispatch(Long id, String reason);

    boolean reassignTeam(Long assignmentId, Long newTeamId);
}
