# Generated by Django 6.0.6 on 2026-06-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('clients', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='客户经理'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='client',
            name='intro_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced', to='clients.client', verbose_name='介绍人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='cases.case', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='委托方(客户)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='firm_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='律所签约人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='documents.documenttemplate', verbose_name='使用模板'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='clients.contract', verbose_name='合同'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type', 'vip_level'], name='client_clie_client__eefd01_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_no'], name='client_clie_client__c5b7cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplan',
            unique_together={('contract', 'installment_no')},
        ),
    ]
