doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:DATABASE_URL)%'
            options: {}
    default_database: theater_ticket
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
