import { Project, DesignTask, ReviewRecord, ChangeRequest, DesignVersion, User } from '@/types'

export const mockUsers: User[] = [
  { id: 1, username: 'admin', name: '系统管理员', role: 'ADMIN', email: 'admin@design.com' },
  { id: 2, username: 'pm01', name: '张经理', role: 'PROJECT_MANAGER', email: 'zhangpm@design.com' },
  { id: 3, username: 'pm02', name: '王经理', role: 'PROJECT_MANAGER', email: 'wangpm@design.com' },
  { id: 4, username: 'lead_arch', name: '李建筑', role: 'PROFESSIONAL_LEAD', profession: 'ARCHITECTURE' },
  { id: 5, username: 'lead_struct', name: '赵结构', role: 'PROFESSIONAL_LEAD', profession: 'STRUCTURE' },
  { id: 6, username: 'lead_plumb', name: '钱给排水', role: 'PROFESSIONAL_LEAD', profession: 'PLUMBING' },
  { id: 7, username: 'lead_hvac', name: '孙暖通', role: 'PROFESSIONAL_LEAD', profession: 'HVAC' },
  { id: 8, username: 'lead_elec', name: '周电气', role: 'PROFESSIONAL_LEAD', profession: 'ELECTRICAL' },
  { id: 9, username: 'designer01', name: '设计师甲', role: 'DESIGNER', profession: 'ARCHITECTURE' },
  { id: 10, username: 'designer02', name: '设计师乙', role: 'DESIGNER', profession: 'STRUCTURE' },
  { id: 11, username: 'designer03', name: '设计师丙', role: 'DESIGNER', profession: 'PLUMBING' },
  { id: 12, username: 'client01', name: '甲方代表', role: 'CLIENT', email: 'client@example.com' },
]

export const mockProjects: Project[] = [
  {
    id: 1,
    projectNo: 'PRJ-2024-001',
    name: '市民文化中心建设项目',
    type: 'GOVERNMENT',
    stage: 'CONSTRUCTION',
    status: 'IN_PROGRESS',
    contractAmount: 8500000,
    startDate: '2024-01-15',
    endDate: '2024-12-30',
    clientName: '市文化局',
    clientContact: '刘主任',
    clientPhone: '13900001111',
    projectManagerId: 2,
    projectManagerName: '张经理',
    description: '市民文化中心建设项目，包括图书馆、展览馆、剧场等多功能综合建筑',
    progress: 65,
    createdAt: '2024-01-10 09:00:00',
    updatedAt: '2024-06-15 14:30:00',
  },
  {
    id: 2,
    projectNo: 'PRJ-2024-002',
    name: '滨江商业综合体',
    type: 'COMMERCIAL',
    stage: 'PRELIMINARY',
    status: 'IN_PROGRESS',
    contractAmount: 15000000,
    startDate: '2024-03-01',
    endDate: '2025-06-30',
    clientName: '滨江置业有限公司',
    clientContact: '陈总',
    clientPhone: '13900002222',
    projectManagerId: 3,
    projectManagerName: '王经理',
    description: '集购物、餐饮、娱乐、办公于一体的大型商业综合体',
    progress: 30,
    createdAt: '2024-02-20 10:00:00',
    updatedAt: '2024-06-10 16:00:00',
  },
  {
    id: 3,
    projectNo: 'PRJ-2024-003',
    name: '智能制造产业园厂房',
    type: 'INDUSTRIAL',
    stage: 'SCHEME',
    status: 'PENDING',
    contractAmount: 5200000,
    startDate: '2024-07-01',
    endDate: '2025-03-31',
    clientName: '未来科技有限公司',
    clientContact: '吴工',
    clientPhone: '13900003333',
    projectManagerId: 2,
    projectManagerName: '张经理',
    description: '智能制造产业园区标准厂房及配套设施设计',
    progress: 0,
    createdAt: '2024-06-01 11:00:00',
    updatedAt: '2024-06-15 09:00:00',
  },
  {
    id: 4,
    projectNo: 'PRJ-2024-004',
    name: '政务服务中心改造',
    type: 'GOVERNMENT',
    stage: 'SCHEME',
    status: 'REVIEWING',
    contractAmount: 3200000,
    startDate: '2024-05-01',
    endDate: '2024-11-30',
    clientName: '市政务服务中心',
    clientContact: '郑主任',
    clientPhone: '13900004444',
    projectManagerId: 3,
    projectManagerName: '王经理',
    description: '政务服务中心内部空间改造及功能优化设计',
    progress: 25,
    createdAt: '2024-04-20 14:00:00',
    updatedAt: '2024-06-14 17:00:00',
  },
  {
    id: 5,
    projectNo: 'PRJ-2024-005',
    name: '高端住宅社区一期',
    type: 'COMMERCIAL',
    stage: 'CONSTRUCTION',
    status: 'COMPLETED',
    contractAmount: 12000000,
    startDate: '2023-06-01',
    endDate: '2024-05-31',
    clientName: '绿城地产集团',
    clientContact: '黄总',
    clientPhone: '13900005555',
    projectManagerId: 2,
    projectManagerName: '张经理',
    description: '高端住宅社区一期工程施工图设计',
    progress: 100,
    createdAt: '2023-05-20 09:00:00',
    updatedAt: '2024-05-30 18:00:00',
  },
]

export const mockTasks: DesignTask[] = [
  {
    id: 1,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    stage: 'CONSTRUCTION',
    profession: 'ARCHITECTURE',
    name: '建筑施工图-平面图绘制',
    description: '完成各楼层建筑平面布置图',
    assigneeId: 9,
    assigneeName: '设计师甲',
    status: 'IN_PROGRESS',
    progress: 75,
    plannedStartDate: '2024-05-01',
    plannedEndDate: '2024-06-30',
    actualStartDate: '2024-05-02',
    deliverables: '平面施工图CAD文件',
    createdAt: '2024-04-25 10:00:00',
    updatedAt: '2024-06-15 14:00:00',
  },
  {
    id: 2,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    stage: 'CONSTRUCTION',
    profession: 'STRUCTURE',
    name: '结构施工图-基础设计',
    description: '完成基础结构设计及计算书',
    assigneeId: 10,
    assigneeName: '设计师乙',
    status: 'REVIEWING',
    progress: 90,
    plannedStartDate: '2024-05-10',
    plannedEndDate: '2024-07-10',
    actualStartDate: '2024-05-10',
    deliverables: '基础施工图及计算书',
    createdAt: '2024-05-05 10:00:00',
    updatedAt: '2024-06-14 16:00:00',
  },
  {
    id: 3,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    stage: 'CONSTRUCTION',
    profession: 'PLUMBING',
    name: '给排水系统设计',
    description: '完成室内外给排水系统设计',
    assigneeId: 11,
    assigneeName: '设计师丙',
    status: 'PENDING',
    progress: 0,
    plannedStartDate: '2024-06-15',
    plannedEndDate: '2024-07-30',
    deliverables: '给排水系统施工图',
    createdAt: '2024-06-01 10:00:00',
    updatedAt: '2024-06-01 10:00:00',
  },
  {
    id: 4,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    stage: 'CONSTRUCTION',
    profession: 'HVAC',
    name: '暖通空调系统设计',
    description: '完成暖通空调系统方案及施工图',
    status: 'PENDING',
    progress: 0,
    plannedStartDate: '2024-06-20',
    plannedEndDate: '2024-08-15',
    deliverables: '暖通空调系统施工图',
    createdAt: '2024-06-01 10:00:00',
    updatedAt: '2024-06-01 10:00:00',
  },
  {
    id: 5,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    stage: 'CONSTRUCTION',
    profession: 'ELECTRICAL',
    name: '电气系统设计',
    description: '完成强电、弱电系统设计',
    assigneeId: 9,
    assigneeName: '设计师甲',
    status: 'COMPLETED',
    progress: 100,
    plannedStartDate: '2024-04-01',
    plannedEndDate: '2024-05-30',
    actualStartDate: '2024-04-02',
    actualEndDate: '2024-05-28',
    deliverables: '电气系统施工图',
    createdAt: '2024-03-25 10:00:00',
    updatedAt: '2024-05-28 17:00:00',
  },
  {
    id: 6,
    projectId: 2,
    projectName: '滨江商业综合体',
    stage: 'PRELIMINARY',
    profession: 'ARCHITECTURE',
    name: '方案深化设计',
    description: '根据方案评审意见进行深化设计',
    assigneeId: 9,
    assigneeName: '设计师甲',
    status: 'IN_PROGRESS',
    progress: 50,
    plannedStartDate: '2024-05-15',
    plannedEndDate: '2024-07-15',
    actualStartDate: '2024-05-16',
    deliverables: '初步设计图纸',
    createdAt: '2024-05-10 10:00:00',
    updatedAt: '2024-06-15 10:00:00',
  },
  {
    id: 7,
    projectId: 2,
    projectName: '滨江商业综合体',
    stage: 'PRELIMINARY',
    profession: 'STRUCTURE',
    name: '结构方案选型',
    description: '进行结构方案比选及优化',
    status: 'PENDING',
    progress: 0,
    plannedStartDate: '2024-06-20',
    plannedEndDate: '2024-07-30',
    deliverables: '结构方案设计报告',
    createdAt: '2024-06-10 10:00:00',
    updatedAt: '2024-06-10 10:00:00',
  },
]

export const mockReviews: ReviewRecord[] = [
  {
    id: 1,
    taskId: 2,
    projectId: 1,
    versionId: 1,
    level: 'CHECK',
    reviewerId: 5,
    reviewerName: '赵结构',
    status: 'IN_PROGRESS',
    submittedAt: '2024-06-14 09:00:00',
    comments: [
      {
        id: 1,
        reviewRecordId: 1,
        content: '基础筏板配筋偏小，建议复核计算',
        location: '基础平面图 1-A轴交3轴',
        resolved: false,
        createdBy: 5,
        createdByName: '赵结构',
        createdAt: '2024-06-14 10:30:00',
      },
      {
        id: 2,
        reviewRecordId: 1,
        content: '地下室外墙裂缝控制措施需补充',
        location: '地下一层墙身详图',
        reply: '已补充温度应力钢筋及后浇带设置说明',
        resolved: true,
        createdBy: 5,
        createdByName: '赵结构',
        createdAt: '2024-06-14 11:00:00',
        repliedAt: '2024-06-14 15:30:00',
      },
    ],
  },
  {
    id: 2,
    taskId: 5,
    projectId: 1,
    versionId: 3,
    level: 'AUDIT',
    reviewerId: 8,
    reviewerName: '周电气',
    status: 'PASSED',
    submittedAt: '2024-05-25 09:00:00',
    completedAt: '2024-05-27 16:00:00',
    comments: [
      {
        id: 3,
        reviewRecordId: 2,
        content: '配电系统图符合规范要求',
        resolved: true,
        createdBy: 8,
        createdByName: '周电气',
        createdAt: '2024-05-26 10:00:00',
      },
    ],
  },
]

export const mockChanges: ChangeRequest[] = [
  {
    id: 1,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    changeNo: 'CR-2024-001',
    title: '剧场舞台区域层高调整',
    reason: '舞台机械安装高度要求增加',
    content: '将剧场舞台区域层高从12米调整为15米，相应调整屋面结构标高',
    impactScope: '建筑专业：立面调整、剖面重绘；结构专业：屋面结构重新计算',
    workload: 40,
    additionalFee: 80000,
    status: 'PM_APPROVED',
    applicantId: 12,
    applicantName: '甲方代表',
    applicantType: 'CLIENT',
    currentApproverId: 4,
    createdAt: '2024-06-10 14:00:00',
    approvalRecords: [
      {
        id: 1,
        changeRequestId: 1,
        approverId: 2,
        approverName: '张经理',
        approverRole: 'PROJECT_MANAGER',
        comment: '情况属实，同意变更申请',
        approved: true,
        approvedAt: '2024-06-11 10:00:00',
      },
    ],
  },
  {
    id: 2,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    changeNo: 'CR-2024-002',
    title: '图书馆阅览区采光优化',
    reason: '原设计采光不足，需增加天窗',
    content: '在图书馆阅览区屋面增设三处采光天窗，面积约60平米',
    impactScope: '建筑：屋面增加天窗；结构：屋面开洞加固；给排水：屋面排水重新设计',
    workload: 25,
    additionalFee: 50000,
    status: 'SUBMITTED',
    applicantId: 4,
    applicantName: '李建筑',
    applicantType: 'INTERNAL',
    currentApproverId: 2,
    createdAt: '2024-06-14 09:30:00',
    approvalRecords: [],
  },
  {
    id: 3,
    projectId: 5,
    projectName: '高端住宅社区一期',
    changeNo: 'CR-2024-003',
    title: '外墙保温材料变更',
    reason: '消防规范要求提高，原材料不满足新规范',
    content: '外墙保温材料由XPS板更换为岩棉板，厚度相应调整',
    impactScope: '建筑：外墙构造节点修改；节能计算重新验算',
    workload: 15,
    additionalFee: 30000,
    status: 'IMPLEMENTED',
    applicantId: 4,
    applicantName: '李建筑',
    applicantType: 'INTERNAL',
    createdAt: '2024-03-15 10:00:00',
    approvalRecords: [
      {
        id: 2,
        changeRequestId: 3,
        approverId: 2,
        approverName: '张经理',
        approverRole: 'PROJECT_MANAGER',
        approved: true,
        approvedAt: '2024-03-15 14:00:00',
      },
      {
        id: 3,
        changeRequestId: 3,
        approverId: 4,
        approverName: '李建筑',
        approverRole: 'PROFESSIONAL_LEAD',
        approved: true,
        approvedAt: '2024-03-16 09:00:00',
      },
      {
        id: 4,
        changeRequestId: 3,
        approverId: 12,
        approverName: '甲方代表',
        approverRole: 'CLIENT',
        comment: '同意变更，费用按合同执行',
        approved: true,
        approvedAt: '2024-03-17 11:00:00',
      },
    ],
  },
]

export const mockVersions: DesignVersion[] = [
  {
    id: 1,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    taskId: 2,
    versionNo: 'V1.0',
    fileName: '市民文化中心_结构基础施工图.dwg',
    fileSize: 15234567,
    filePath: '/files/projects/1/tasks/2/v1.0.dwg',
    uploadedBy: 10,
    uploadedByName: '设计师乙',
    description: '结构基础施工图初稿',
    isReleased: false,
    createdAt: '2024-06-10 14:00:00',
  },
  {
    id: 2,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    taskId: 2,
    versionNo: 'V1.1',
    fileName: '市民文化中心_结构基础施工图_v1.1.dwg',
    fileSize: 15890234,
    filePath: '/files/projects/1/tasks/2/v1.1.dwg',
    uploadedBy: 10,
    uploadedByName: '设计师乙',
    description: '根据校对意见修改：调整筏板配筋、补充外墙裂缝控制措施',
    isReleased: false,
    createdAt: '2024-06-14 16:00:00',
  },
  {
    id: 3,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    taskId: 5,
    versionNo: 'V1.0',
    fileName: '市民文化中心_电气系统施工图.dwg',
    fileSize: 23456789,
    filePath: '/files/projects/1/tasks/5/v1.0.dwg',
    uploadedBy: 9,
    uploadedByName: '设计师甲',
    description: '电气系统施工图（强电+弱电）最终版',
    isReleased: true,
    createdAt: '2024-05-28 17:00:00',
  },
  {
    id: 4,
    projectId: 1,
    projectName: '市民文化中心建设项目',
    taskId: 1,
    versionNo: 'V0.5',
    fileName: '市民文化中心_建筑平面图_草稿.dwg',
    fileSize: 18765432,
    filePath: '/files/projects/1/tasks/1/v0.5.dwg',
    uploadedBy: 9,
    uploadedByName: '设计师甲',
    description: '建筑平面图初稿（3-6层）',
    isReleased: false,
    createdAt: '2024-06-08 15:00:00',
  },
  {
    id: 5,
    projectId: 2,
    projectName: '滨江商业综合体',
    taskId: 6,
    versionNo: 'V0.3',
    fileName: '滨江商业综合体_方案深化_v0.3.pdf',
    fileSize: 45678901,
    filePath: '/files/projects/2/tasks/6/v0.3.pdf',
    uploadedBy: 9,
    uploadedByName: '设计师甲',
    description: '方案深化设计第三版',
    isReleased: false,
    createdAt: '2024-06-12 10:00:00',
  },
]
