server:
  port: 8083

spring:
  application:
    name: icc-task
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iccert?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.iccert.task.entity
  configuration:
    map-underscore-to-camel-case: true

dispatch:
  algorithm:
    load-weight: 0.6
    skill-weight: 0.4
    max-workload: 85

springdoc:
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn
