package com.emergency.incident.feign;

import com.emergency.common.result.Result;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.web.bind.annotation.*;

@FeignClient(name = "dispatch-service", path = "/api/dispatch")
public interface DispatchFeignClient {

    @PostMapping("/dispatches/auto-generate")
    Result<Long> autoGenerateDispatch(@RequestParam Long incidentId);

    @GetMapping("/dispatches/incident/{incidentId}")
    Result<Object> getDispatchByIncidentId(@PathVariable Long incidentId);
}
