// Package docs provides placeholder swagger doc files generated by swaggo/swag.
// Run `swag init -g cmd/server/main.go -o docs` to regenerate.
package docs

// SwaggerInfo holds exported swagger info so that the user can set them programmatically.
type SwaggerInfo struct {
	InstanceName string
	Schemes      []string
	Host         string
	BasePath     string
	Title        string
	Description  string
	Version      string
}

// SwaggerInstance is the exported singleton instance of swagger info.
var SwaggerInstance SwaggerInfo = SwaggerInfo{
	InstanceName: "swagger",
	Host:         "localhost:8080",
	BasePath:     "/",
	Schemes:      []string{"http", "https"},
	Title:        "精酿啤酒批次生产追踪与质量合规系统 API",
	Description:  "支撑从原料入库到灌装出库的全链路批次管理与质检。完整文档可通过 swag init 生成。",
	Version:      "1.0.0",
}
