// Package models defines the shared domain types used across the gas pipeline
// scheduling assistant: stations, pipelines, meter readings, dispatch
// instructions, balance plans and audit records.
package models

import "time"

// StationType classifies a metering/supply point on the network.
type StationType string

const (
	StationTypeSource      StationType = "source"      // 上游气源站
	StationTypeTransit     StationType = "transit"     // 分输站
	StationTypeValve       StationType = "valve"       // 阀室
	StationTypeCityUser    StationType = "city_user"   // 城市燃气公司
	StationTypeIndustrial  StationType = "industrial"  // 工业直供用户
)

// Station describes a physical node on the pipeline network.
type Station struct {
	ID            string      `json:"id" yaml:"id"`
	Name          string      `json:"name" yaml:"name"`
	Type          StationType `json:"type" yaml:"type"`
	Address       string      `json:"address" yaml:"address"`         // Modbus TCP host:port
	UnitID        byte        `json:"unit_id" yaml:"unit_id"`         // Modbus slave id
	Pipeline      string      `json:"pipeline" yaml:"pipeline"`      // 所属管段编号
	Elevation     float64     `json:"elevation" yaml:"elevation"`     // 高程差(m)
	// Modbus register addresses for the four measured quantities.
	RegPressure   uint16      `json:"reg_pressure" yaml:"reg_pressure"`
	RegTemperature uint16     `json:"reg_temperature" yaml:"reg_temperature"`
	RegFlow       uint16      `json:"reg_flow" yaml:"reg_flow"`
	RegAccum      uint16      `json:"reg_accum" yaml:"reg_accum"`
	// Value domain used for integrity validation.
	PressureMin   float64     `json:"pressure_min" yaml:"pressure_min"`
	PressureMax   float64     `json:"pressure_max" yaml:"pressure_max"`
	TempMin       float64     `json:"temp_min" yaml:"temp_min"`
	TempMax       float64     `json:"temp_max" yaml:"temp_max"`
	FlowMin       float64     `json:"flow_min" yaml:"flow_min"`
	FlowMax       float64     `json:"flow_max" yaml:"flow_max"`
}

// PipelineSegment describes one section of trunk line between two stations.
type PipelineSegment struct {
	ID           string  `json:"id" yaml:"id"`
	Name         string  `json:"name" yaml:"name"`
	FromStation  string  `json:"from_station" yaml:"from_station"`
	ToStation    string  `json:"to_station" yaml:"to_station"`
	Length       float64 `json:"length" yaml:"length"`          // km
	Diameter     float64 `json:"diameter" yaml:"diameter"`      // mm 内径
	Roughness    float64 `json:"roughness" yaml:"roughness"`     // mm 绝对粗糙度
	ElevationDiff float64 `json:"elevation_diff" yaml:"elevation_diff"` // m
	Formula      string  `json:"formula" yaml:"formula"`        // weymouth | panhandle
	BaseTemp     float64 `json:"base_temp" yaml:"base_temp"`    // K 基准温度
	BasePressure float64 `json:"base_pressure" yaml:"base_pressure"` // MPa 基准压力
	GasGravity   float64 `json:"gas_gravity" yaml:"gas_gravity"` // 天然气相对密度
	CompressFactor float64 `json:"compress_factor" yaml:"compress_factor"` // 压缩因子
	Efficiency   float64 `json:"efficiency" yaml:"efficiency"`     // Panhole 传输效率 E (0-1)
	Coefficient  float64 `json:"coefficient" yaml:"coefficient"`    // 公式系数覆盖(>0 时覆盖默认 K)
}

// Reading is a single polled instantaneous measurement from a station.
type Reading struct {
	ID           int64     `json:"id"`
	StationID    string    `json:"station_id"`
	Timestamp    time.Time `json:"timestamp"`
	Pressure     float64   `json:"pressure"`      // MPa
	Temperature  float64   `json:"temperature"`   // ℃
	FlowRate     float64   `json:"flow_rate"`      // Nm3/h 瞬时流量
	Accumulated  float64   `json:"accumulated"`    // Nm3 累计量
	Valid        bool      `json:"valid"`         // 数据完整性校验结果
	Anomaly      string    `json:"anomaly"`        // 异常原因，空表示正常
	CollectedAt  time.Time `json:"collected_at"`
}

// PressureLossResult is the computed pressure drop for a pipeline segment.
type PressureLossResult struct {
	SegmentID       string  `json:"segment_id"`
	SegmentName     string  `json:"segment_name"`
	UpstreamStation string  `json:"upstream_station"`
	DownstreamStation string `json:"downstream_station"`
	InletPressure   float64 `json:"inlet_pressure"`  // MPa
	OutletPressure  float64 `json:"outlet_pressure"` // MPa
	PressureLoss    float64 `json:"pressure_loss"`   // MPa
	LossPercent     float64 `json:"loss_percent"`    // %
	SafetyMargin    float64 `json:"safety_margin"`   // MPa 距离报警阈值的安全裕度
	Formula         string  `json:"formula"`
	Timestamp       time.Time `json:"timestamp"`
}

// DemandPlan captures one downstream user's requested supply for a window.
type DemandPlan struct {
	UserID     string  `json:"user_id"`
	UserName   string  `json:"user_name"`
	Demand     float64 `json:"demand"`      // Nm3/h
	Priority   int     `json:"priority"`    // 1 高 ... 3 低
	UnitPrice  float64 `json:"unit_price"`  // 元/Nm3
}

// BalancePlan is one candidate upstream regulation scheme generated by the
// supply-demand balance engine.
type BalancePlan struct {
	ID            string       `json:"id"`
	TotalDemand   float64      `json:"total_demand"`   // Nm3/h
	TotalSupply   float64      `json:"total_supply"`   // Nm3/h
	Imbalance     float64      `json:"imbalance"`      // Nm3/h 供需差
	SourceRegulations []SourceRegulation `json:"source_regulations"`
	EnergyCost    float64      `json:"energy_cost"`    // 元 综合能耗成本
	SafetyScore   float64      `json:"safety_score"`   // 0-100 安全评估
	Recommended   bool         `json:"recommended"`
}

// SourceRegulation is the upstream adjustment within a balance plan.
type SourceRegulation struct {
	SourceID    string  `json:"source_id"`
	SourceName  string  `json:"source_name"`
	TargetPressure float64 `json:"target_pressure"` // MPa
	TargetFlow  float64 `json:"target_flow"`       // Nm3/h
	CostPerUnit float64 `json:"cost_per_unit"`     // 元/Nm3
}

// Urgency ranks dispatch instructions by emergency level.
type Urgency string

const (
	UrgencyCritical Urgency = "critical" // 紧急
	UrgencyHigh     Urgency = "high"     // 高
	UrgencyNormal   Urgency = "normal"   // 常规
	UrgencyLow      Urgency = "low"      // 低
)

// DispatchInstruction is a standardised textual command for an operator.
type DispatchInstruction struct {
	ID           string    `json:"id"`
	StationID    string    `json:"station_id"`
	StationName  string    `json:"station_name"`
	Urgency      Urgency   `json:"urgency"`
	AdjustType   string    `json:"adjust_type"`   // pressure | flow | valve
	TargetValue  float64   `json:"target_value"`
	Current      float64   `json:"current"`
	ExecuteFrom  time.Time `json:"execute_from"`
	ExecuteTo    time.Time `json:"execute_to"`
	SafetyNotes  string    `json:"safety_notes"`
	Operator     string    `json:"operator"`
	Status       string    `json:"status"` // draft | issued | executed | failed
	Reason       string    `json:"reason"`
	CreatedAt    time.Time `json:"created_at"`
}

// PriceContract records a downstream user's monthly settlement terms.
type PriceContract struct {
	UserID    string  `json:"user_id"`
	UserName  string  `json:"user_name"`
	UnitPrice float64 `json:"unit_price"` // 元/Nm3
	TaxRate   float64 `json:"tax_rate"`   // 税率
}

// SettlementRow is one line of the monthly settlement report.
type SettlementRow struct {
	UserID        string  `json:"user_id"`
	UserName      string  `json:"user_name"`
	Volume        float64 `json:"volume"`         // Nm3 累计购气量
	UnitPrice     float64 `json:"unit_price"`      // 元/Nm3
	Amount        float64 `json:"amount"`          // 结算金额(不含税)
	TaxAmount     float64 `json:"tax_amount"`      // 税额
	TotalAmount   float64 `json:"total_amount"`    // 含税金额
	Month         string  `json:"month"`           // YYYY-MM
}

// AuditLog records a configuration or operational change for traceability.
type AuditLog struct {
	ID        int64     `json:"id"`
	Action    string    `json:"action"`    // config_change | dispatch_issue | ...
	Operator  string    `json:"operator"`
	Detail    string    `json:"detail"`
	ChangedAt time.Time `json:"changed_at"`
}

// ValidateDomain checks a reading against the station value ranges and the
// presence of mandatory fields. It returns the (possibly marked) reading and
// a human readable anomaly reason (empty when valid).
func (r Reading) ValidateDomain(s Station) (Reading, string) {
	if r.StationID == "" {
		r.Valid = false
		r.Anomaly = "missing station id"
		return r, r.Anomaly
	}
	if r.Timestamp.IsZero() {
		r.Valid = false
		r.Anomaly = "missing timestamp"
		return r, r.Anomaly
	}
	if !inRange(r.Pressure, s.PressureMin, s.PressureMax) {
		r.Valid = false
		r.Anomaly = "pressure out of range"
		return r, r.Anomaly
	}
	if !inRange(r.Temperature, s.TempMin, s.TempMax) {
		r.Valid = false
		r.Anomaly = "temperature out of range"
		return r, r.Anomaly
	}
	if !inRange(r.FlowRate, s.FlowMin, s.FlowMax) {
		r.Valid = false
		r.Anomaly = "flow rate out of range"
		return r, r.Anomaly
	}
	if r.Accumulated < 0 {
		r.Valid = false
		r.Anomaly = "accumulated volume negative"
		return r, r.Anomaly
	}
	r.Valid = true
	r.Anomaly = ""
	return r, ""
}

func inRange(v, lo, hi float64) bool {
	return v >= lo && v <= hi
}
