server:
  port: 9200

spring:
  application:
    name: artifact-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: heritage_artifact
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1GB

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: heritage-artifacts

logging:
  level:
    com.heritage.artifact: DEBUG
