package com.emergency.dispatch.controller;

import com.emergency.common.dto.PageResult;
import com.emergency.common.result.Result;
import com.emergency.dispatch.dto.DispatchConflictResult;
import com.emergency.dispatch.dto.DispatchGenerateRequest;
import com.emergency.dispatch.entity.DispatchPlan;
import com.emergency.dispatch.entity.RescueTeam;
import com.emergency.dispatch.entity.TeamAssignment;
import com.emergency.dispatch.service.DispatchService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/dispatches")
@RequiredArgsConstructor
@Tag(name = "救援调度管理", description = "救援力量调度接口")
public class DispatchController {

    private final DispatchService dispatchService;

    @PostMapping("/auto-generate")
    @Operation(summary = "自动生成调度方案")
    public Result<Long> autoGenerateDispatch(@Parameter(description = "灾情ID") @RequestParam Long incidentId) {
        return Result.success(dispatchService.autoGenerateDispatch(incidentId));
    }

    @PostMapping("/generate")
    @Operation(summary = "手动生成调度方案")
    public Result<DispatchPlan> generateDispatchPlan(@Valid @RequestBody DispatchGenerateRequest request) {
        return Result.success(dispatchService.generateDispatchPlan(request));
    }

    @GetMapping("/{id}")
    @Operation(summary = "获取调度方案详情")
    public Result<DispatchPlan> getDispatchById(@PathVariable Long id) {
        return Result.success(dispatchService.getDispatchById(id));
    }

    @GetMapping("/no/{dispatchNo}")
    @Operation(summary = "根据编号获取调度方案")
    public Result<DispatchPlan> getDispatchByNo(@PathVariable String dispatchNo) {
        return Result.success(dispatchService.getDispatchByNo(dispatchNo));
    }

    @GetMapping("/incident/{incidentId}")
    @Operation(summary = "获取灾情关联的调度方案")
    public Result<List<DispatchPlan>> getDispatchByIncidentId(@PathVariable Long incidentId) {
        return Result.success(dispatchService.getDispatchByIncidentId(incidentId));
    }

    @GetMapping("/active")
    @Operation(summary = "获取活跃调度方案")
    public Result<List<DispatchPlan>> getActiveDispatchPlans() {
        return Result.success(dispatchService.getActiveDispatchPlans());
    }

    @GetMapping("/list")
    @Operation(summary = "分页查询调度方案")
    public Result<PageResult<DispatchPlan>> queryDispatchPlans(
            @RequestParam(defaultValue = "1") int pageNum,
            @RequestParam(defaultValue = "10") int pageSize,
            @RequestParam(required = false) Integer status,
            @RequestParam(required = false) String regionCode) {
        return Result.success(dispatchService.queryDispatchPlans(pageNum, pageSize, status, regionCode));
    }

    @PutMapping("/{id}/status")
    @Operation(summary = "更新调度方案状态")
    public Result<DispatchPlan> updateDispatchStatus(
            @PathVariable Long id,
            @Parameter(description = "状态:1-待审批 2-已批准 3-已派出 4-执行中 5-已完成 7-已取消") @RequestParam Integer status) {
        return Result.success(dispatchService.updateDispatchStatus(id, status));
    }

    @PostMapping("/check-conflicts")
    @Operation(summary = "检测调度冲突")
    public Result<DispatchConflictResult> checkConflicts(
            @RequestParam Long incidentId,
            @RequestParam List<Long> teamIds) {
        return Result.success(dispatchService.checkConflicts(incidentId, teamIds));
    }

    @GetMapping("/teams/available")
    @Operation(summary = "获取附近可用队伍")
    public Result<List<RescueTeam>> getAvailableTeams(
            @Parameter(description = "经度") @RequestParam Double lng,
            @Parameter(description = "纬度") @RequestParam Double lat,
            @Parameter(description = "查询半径(公里)") @RequestParam(defaultValue = "50") Double radius,
            @Parameter(description = "返回数量") @RequestParam(defaultValue = "10") Integer limit) {
        return Result.success(dispatchService.getAvailableTeams(lng, lat, radius, limit));
    }

    @GetMapping("/teams")
    @Operation(summary = "获取所有救援队伍")
    public Result<List<RescueTeam>> getAllTeams() {
        return Result.success(dispatchService.getAllTeams());
    }

    @GetMapping("/teams/{id}")
    @Operation(summary = "获取队伍详情")
    public Result<RescueTeam> getTeamById(@PathVariable Long id) {
        return Result.success(dispatchService.getTeamById(id));
    }

    @GetMapping("/{id}/assignments")
    @Operation(summary = "获取调度方案的队伍分配")
    public Result<List<TeamAssignment>> getTeamAssignments(@PathVariable Long id) {
        return Result.success(dispatchService.getTeamAssignmentsByPlanId(id));
    }

    @PostMapping("/{id}/cancel")
    @Operation(summary = "取消调度方案")
    public Result<Boolean> cancelDispatch(
            @PathVariable Long id,
            @Parameter(description = "取消原因") @RequestParam String reason) {
        return Result.success(dispatchService.cancelDispatch(id, reason));
    }

    @PostMapping("/assignments/{assignmentId}/reassign")
    @Operation(summary = "重新分配队伍")
    public Result<Boolean> reassignTeam(
            @PathVariable Long assignmentId,
            @Parameter(description = "新队伍ID") @RequestParam Long newTeamId) {
        return Result.success(dispatchService.reassignTeam(assignmentId, newTeamId));
    }
}
