framework:
    secret: '%env(APP_SECRET)%'
    default_locale: zh_CN
    csrf_protection: true
    http_method_override: false
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    validation:
        enable_annotations: true
