controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_auth_login:
    path: /api/auth/login
    methods: [POST]

kernel:
    resource: ../src/Kernel.php
    type: attribute
