# Generated by Django 6.0.6 on 2026-06-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_evidence_has_ocr_evidence_watermark_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('category', models.CharField(choices=[('case_status', '案件状态变更'), ('limitation_warning', '诉讼时效预警'), ('trial_reminder', '庭审提醒'), ('evidence_alert', '证据风险'), ('billing_reminder', '费用提醒'), ('system', '系统通知'), ('approval', '审批通知'), ('other', '其他')], default='system', max_length=30, verbose_name='消息分类')),
                ('level', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('urgent', '紧急'), ('critical', '严重')], default='info', max_length=20, verbose_name='紧急程度')),
                ('channel', models.CharField(choices=[('in_app', '站内消息'), ('sms', '短信推送'), ('app_push', 'APP推送'), ('email', '邮件通知')], default='in_app', max_length=20, verbose_name='推送渠道')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case', verbose_name='关联案件')),
                ('related_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cases.trial', verbose_name='关联庭审')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'sys_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='sys_notific_recipie_33e96c_idx'), models.Index(fields=['category', 'created_at'], name='sys_notific_categor_9fbc51_idx')],
            },
        ),
    ]
