import os, sys, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
django.setup()
from apps.users.models import User
from apps.documents.models import DocumentTemplate
from decimal import Decimal

admin = User.objects.get(username='admin')

templates = [
    ('civil_complaint', '民事起诉状', '适用于一般民事纠纷一审起诉', 'civil'),
    ('civil_complaint', '民间借贷纠纷起诉状', '借款纠纷、利息、违约金诉讼', 'civil'),
    ('civil_complaint', '买卖合同纠纷起诉状', '货款、交付、质量争议起诉状', 'commercial'),
    ('civil_complaint', '房屋买卖合同纠纷起诉状', '商品房/二手房买卖纠纷', 'civil'),
    ('civil_complaint', '租赁合同纠纷起诉状', '房屋/设备租赁争议起诉状', 'civil'),
    ('civil_complaint', '离婚起诉状', '婚姻关系解除、财产分割、子女抚养', 'family'),
    ('civil_complaint', '交通事故损害赔偿起诉状', '人身财产损害赔偿诉讼', 'civil'),
    ('civil_complaint', '医疗损害责任纠纷起诉状', '医疗过错赔偿诉讼', 'civil'),
    ('civil_complaint', '建设工程施工合同纠纷起诉状', '工程款、工期、质量争议', 'commercial'),
    ('civil_complaint', '知识产权侵权起诉状', '著作权/商标/专利侵权诉讼', 'ip'),
    ('civil_complaint', '劳动争议起诉状', '不服仲裁裁决提起诉讼', 'labor'),
    ('civil_defense', '民事答辩状', '被告方应诉答辩使用', 'civil'),
    ('civil_defense', '民间借贷纠纷答辩状', '借款纠纷被告抗辩意见', 'civil'),
    ('civil_defense', '合同纠纷答辩状', '合同争议被告答辩意见', 'commercial'),
    ('civil_defense', '交通事故答辩状', '交通事故损害赔偿答辩', 'civil'),
    ('civil_defense', '离婚案件答辩状', '离婚诉讼中被告方答辩', 'family'),
    ('civil_defense', '劳动争议答辩状', '用人单位/劳动者答辩意见', 'labor'),
    ('civil_defense', '知识产权侵权答辩状', '著作权/商标/专利侵权抗辩', 'ip'),
    ('civil_agent', '民事代理词', '律师庭审后提交代理意见', 'civil'),
    ('civil_agent', '合同纠纷代理词', '合同争议庭审代理意见', 'commercial'),
    ('civil_agent', '民间借贷代理词', '借贷纠纷庭审代理意见', 'civil'),
    ('civil_agent', '婚姻家事代理词', '离婚/财产/抚养案件代理词', 'family'),
    ('civil_agent', '交通事故代理词', '损害赔偿案件庭审代理意见', 'civil'),
    ('civil_agent', '劳动争议代理词', '劳动争议案件代理意见', 'labor'),
    ('civil_agent', '建设工程代理词', '工程款纠纷案件代理意见', 'commercial'),
    ('civil_agent', '知识产权代理词', '知识产权案件庭审代理意见', 'ip'),
    ('criminal_defense', '刑事辩护词', '刑事案件被告人辩护词', 'criminal'),
    ('criminal_defense', '盗窃罪辩护词', '盗窃案件从轻减轻辩护意见', 'criminal'),
    ('criminal_defense', '诈骗罪辩护词', '诈骗犯罪无罪/罪轻辩护', 'criminal'),
    ('criminal_defense', '故意伤害罪辩护词', '故意伤害案件辩护意见', 'criminal'),
    ('criminal_defense', '交通肇事罪辩护词', '交通肇事刑事案件辩护', 'criminal'),
    ('criminal_defense', '职务犯罪辩护词', '贪污/受贿/挪用公款案件辩护', 'criminal'),
    ('criminal_defense', '非法吸收公众存款辩护词', '非法集资类案件辩护', 'criminal'),
    ('criminal_defense', '刑事上诉状', '不服一审刑事判决上诉', 'criminal'),
    ('criminal_complaint', '刑事控告书', '被害人向公安机关/检察院控告', 'criminal'),
    ('criminal_complaint', '刑事自诉状', '被害人直接向法院自诉', 'criminal'),
    ('criminal_complaint', '取保候审申请书', '为犯罪嫌疑人申请取保候审', 'criminal'),
    ('criminal_complaint', '羁押必要性审查申请书', '申请变更羁押强制措施', 'criminal'),
    ('criminal_complaint', '刑事附带民事起诉状', '刑事案件中附带民事赔偿', 'criminal'),
    ('appellate', '民事上诉状', '不服一审判决上诉使用', 'civil'),
    ('appellate', '民事再审申请书', '对生效判决申请再审', 'civil'),
    ('appellate', '行政上诉状', '不服一审行政判决上诉', 'administrative'),
    ('appellate', '刑事上诉状', '不服一审刑事判决上诉', 'criminal'),
    ('appellate', '执行异议申请书', '对执行标的/行为提出异议', 'execution'),
    ('appellate', '第三人撤销之诉起诉状', '第三人撤销生效裁判文书', 'civil'),
    ('application', '执行申请书', '申请强制执行使用', 'execution'),
    ('application', '财产保全申请书', '诉前/诉中财产保全申请', 'civil'),
    ('application', '证据保全申请书', '申请对证据进行固定保全', 'civil'),
    ('application', '调查取证申请书', '申请法院调查收集证据', 'civil'),
    ('application', '司法鉴定申请书', '申请专业司法鉴定', 'civil'),
    ('application', '证人出庭申请书', '申请证人出庭作证', 'civil'),
    ('application', '追加当事人申请书', '申请追加共同原告/被告/第三人', 'civil'),
    ('application', '管辖权异议申请书', '对法院管辖提出异议', 'civil'),
    ('application', '回避申请书', '申请法官/书记员回避', 'civil'),
    ('application', '延期开庭申请书', '申请法院延期开庭审理', 'civil'),
    ('application', '中止诉讼申请书', '申请案件中止审理', 'civil'),
    ('application', '先予执行申请书', '申请先予执行赡养费/抚养费/报酬等', 'civil'),
    ('application', '公示催告申请书', '票据遗失公示催告', 'commercial'),
    ('application', '支付令申请书', '申请法院发出支付令', 'civil'),
    ('application', '破产申请书', '企业破产清算/重整申请', 'commercial'),
    ('application', '行政复议申请书', '不服行政行为申请复议', 'administrative'),
    ('application', '行政起诉状', '提起行政诉讼使用', 'administrative'),
    ('application', '国家赔偿申请书', '申请国家赔偿使用', 'administrative'),
    ('evidence', '证据清单模板', '庭审证据清单及目录', 'all'),
    ('evidence', '证据目录（原告）', '原告方证据分类目录', 'all'),
    ('evidence', '证据目录（被告）', '被告方证据分类目录', 'all'),
    ('evidence', '质证意见模板', '庭审中对对方证据的质证意见', 'all'),
    ('evidence', '证人证言笔录', '询问证人的笔录模板', 'all'),
    ('evidence', '鉴定申请书', '申请司法鉴定的正式文书', 'all'),
    ('contract', '委托代理合同', '事务所标准委托合同', 'non_litigation'),
    ('contract', '常年法律顾问合同', '企业常年法律顾问服务合同', 'non_litigation'),
    ('contract', '专项法律服务合同', '专项法律事务委托合同', 'non_litigation'),
    ('contract', '民事委托代理合同', '民事诉讼案件委托代理', 'civil'),
    ('contract', '刑事辩护委托合同', '刑事辩护案件委托合同', 'criminal'),
    ('contract', '行政诉讼委托合同', '行政案件委托代理合同', 'administrative'),
    ('contract', '非诉讼事务委托合同', '非诉业务委托服务合同', 'non_litigation'),
    ('contract', '法律咨询服务合同', '单项法律咨询服务合同', 'non_litigation'),
    ('legal_opinion', '法律意见书', '专项问题法律咨询意见', 'non_litigation'),
    ('legal_opinion', '合同审查法律意见书', '对合同条款的审查意见', 'commercial'),
    ('legal_opinion', '尽职调查法律意见书', '企业并购/投融资尽调意见', 'commercial'),
    ('legal_opinion', 'IPO法律意见书', '企业上市发行法律意见书', 'commercial'),
    ('legal_opinion', '股权激励方案法律意见书', '员工持股/股权激励意见', 'commercial'),
    ('lawyer_letter', '律师函模板', '正式律师函催告/警告', 'all'),
    ('lawyer_letter', '催款律师函', '追索欠款正式律师函', 'commercial'),
    ('lawyer_letter', '侵权警告律师函', '知识产权/名誉侵权警告', 'ip'),
    ('lawyer_letter', '解除合同律师函', '正式通知解除合同', 'commercial'),
    ('power_of_attorney', '授权委托书', '签署给律师的授权文件', 'all'),
    ('power_of_attorney', '特别授权委托书', '含和解/变更/代收等特别授权', 'all'),
    ('power_of_attorney', '法定代表人身份证明书', '诉讼中法定代表人身份文件', 'all'),
    ('firm_internal', '案件结案报告', '事务所内部结案归档报告', 'all'),
    ('firm_internal', '案件讨论记录', '律所内部案件研讨记录', 'all'),
    ('firm_internal', '客户接待笔录', '法律咨询接谈笔录', 'all'),
    ('firm_internal', '法律风险提示函', '向客户出具的风险告知', 'all'),
    ('firm_internal', '工作日志模板', '律师工作记录模板', 'all'),
    ('firm_internal', '收案审批表', '案件受理内部审批表', 'all'),
]

DocumentTemplate.objects.all().delete()
for cat, name, desc, ctype in templates:
    DocumentTemplate.objects.create(
        template_code=f'TPL-{cat.upper()[:3]}-{abs(hash(name)) % 10000:04d}',
        template_name=name,
        category=cat,
        case_type=ctype,
        description=desc,
        version='1.0',
        is_published=True,
        is_system=True,
        use_count=50 + (hash(cat + name) % 500),
        rating=Decimal('4.3') + Decimal(hash(name) % 7) / Decimal('10'),
        rating_count=20 + (hash(cat) % 80),
        owner=admin,
        tags=[cat, ctype],
        content=f'<h1>{name}</h1><p>[模板说明] {desc}</p><p>模板文件已配置，可从案件详情一键生成。</p>',
        usage_instructions='请在案件管理中关联案件后使用，系统将自动填充当事人、案号等字段。',
    )
print('✅ 创建', DocumentTemplate.objects.count(), '份法律文书模板')
