# Generated by Django 6.0.6 on 2026-06-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_cases', to=settings.AUTH_USER_MODEL, verbose_name='律师助理'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client', verbose_name='委托客户'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='case',
            name='lawyers',
            field=models.ManyToManyField(blank=True, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='参与律师'),
        ),
        migrations.AddField(
            model_name='case',
            name='lead_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_cases', to=settings.AUTH_USER_MODEL, verbose_name='主办律师'),
        ),
        migrations.AddField(
            model_name='caseprogress',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_progress', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='caseprogress',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='cases.case', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='caseprogress',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_evidences', to=settings.AUTH_USER_MODEL, verbose_name='借用人'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='parent_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cases.evidence', verbose_name='父版本'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddField(
            model_name='evidencealert',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.evidence', verbose_name='证据'),
        ),
        migrations.AddField(
            model_name='evidencealert',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='evidenceflow',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='cases.evidence', verbose_name='证据'),
        ),
        migrations.AddField(
            model_name='evidenceflow',
            name='from_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_evidence', to=settings.AUTH_USER_MODEL, verbose_name='从谁'),
        ),
        migrations.AddField(
            model_name='evidenceflow',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='evidenceflow',
            name='to_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_evidence', to=settings.AUTH_USER_MODEL, verbose_name='给谁'),
        ),
        migrations.AddField(
            model_name='party',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='trial',
            name='attending_lawyers',
            field=models.ManyToManyField(blank=True, related_name='attending_trials', to=settings.AUTH_USER_MODEL, verbose_name='出庭律师'),
        ),
        migrations.AddField(
            model_name='trial',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cases.case', verbose_name='案件'),
        ),
        migrations.AddField(
            model_name='trial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trials', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='trial',
            name='presiding_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presiding_trials', to=settings.AUTH_USER_MODEL, verbose_name='出庭主办律师'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'case_type'], name='case_case_status_699867_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['limit_date'], name='case_case_limit_d_25788e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['lead_lawyer'], name='case_case_lead_la_0f28a2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['accept_date'], name='case_case_accept__a2f496_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['case', 'evidence_type'], name='case_eviden_case_id_1db4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['storage_status'], name='case_eviden_storage_84d07a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['barcode'], name='case_eviden_barcode_5d0272_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['start_time'], name='case_trial_start_t_3d4487_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['presiding_lawyer', 'result'], name='case_trial_presidi_87146c_idx'),
        ),
    ]
