# Generated by Django 6.0.6 on 2026-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='has_ocr',
            field=models.BooleanField(default=False, verbose_name='已OCR识别'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='watermark_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='水印配置'),
        ),
    ]
