# Generated by Django 6.0.6 on 2026-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_evidence_has_ocr_evidence_watermark_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='ocr_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='OCR识别信息'),
        ),
        migrations.AlterField(
            model_name='evidenceflow',
            name='action',
            field=models.CharField(choices=[('upload', '上传'), ('borrow', '借出'), ('return', '归还'), ('transfer', '移交'), ('review', '审核'), ('modify', '修改'), ('download', '下载'), ('view', '查看'), ('ocr', 'OCR识别'), ('watermark', '添加水印')], max_length=20, verbose_name='操作类型'),
        ),
    ]
