# Generated by Django 6.0.6 on 2026-06-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('cases', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='开票人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='red_flushed_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice', verbose_name='红冲原发票'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='cases.case', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.contract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlements', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='cases.case', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='clients.client', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='clients.contract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='制单人'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.settlement', verbose_name='关联结算单'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='cases.case', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='clients.client', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='clients.contract', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='参与人员'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='工作人员'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='work_logs',
            field=models.ManyToManyField(blank=True, related_name='settlements', to='billing.worklog', verbose_name='结算工时明细'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='work_logs',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='billing.worklog', verbose_name='关联工时'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['case', 'work_date'], name='billing_wor_case_id_32f747_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['worker', 'work_date'], name='billing_wor_worker__5f0f79_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['approval_status', 'billed'], name='billing_wor_approva_8463ef_idx'),
        ),
    ]
